'use client';

import { BookOpen, FlaskConical, Heart, Wrench } from 'lucide-react';
import { getHobbies, getLanguages, getServices } from '../data';
import { SectionHeading } from './SectionHeading';
import { useLocale } from '../LocaleProvider';

export function AdditionalSections() {
  const { locale, t } = useLocale();
  return <><section className="content-section split-section section-shell" id="lab"><div><SectionHeading index="04" eyebrow={t('homeLab')} title={t('labTitle')} /></div><div className="lab-panel"><div className="lab-icon"><FlaskConical size={22} /></div><div><p className="panel-kicker">{t('personalLab')}</p><h3>{t('practice')}</h3><p>{t('labText')}</p><div className="lab-tags"><span>Ubuntu Linux</span><span>Kubernetes</span><span>kubectl</span><span>k9s</span><span>{t('labTagNetworking')}</span><span>{t('labTagMonitoring')}</span></div></div></div></section><section className="content-section education-section section-shell" id="education"><SectionHeading index="05" eyebrow={t('educationLearning')} title={t('nextLayer')} /><div className="education-grid"><div className="education-primary"><BookOpen size={20} /><p className="panel-kicker">{t('eduDegree')}</p><h3>{t('eduUniversity')}</h3><p>{t('eduText')}</p><div className="language-list"><p className="panel-kicker">{t('languages')}</p>{getLanguages(locale).map((language) => <div className="language-row" key={language.name}><span>{language.name}</span><small>{language.level}</small></div>)}</div></div><div className="learning-path"><p className="panel-kicker">{t('preparing')}</p><div className="learning-item"><span>{t('learnCka')}</span><small>{t('learnCkaSub')}</small></div><div className="learning-item"><span>{t('learnLinux')}</span><small>{t('learnLinuxSub')}</small></div><div className="learning-item"><span>{t('learnAzure')}</span><small>{t('learnAzureSub')}</small></div><p className="future-note">{t('longTerm')}</p></div></div></section><section className="content-section hobbies-section section-shell" id="hobbies"><SectionHeading index="06" eyebrow={t('outside')} title={t('hobbiesTitle')} /><div className="hobbies-grid">{getHobbies(locale).map((hobby) => <article className="hobby-item" key={hobby.title}><Heart size={16} /><h3>{hobby.title}</h3><p>{hobby.text}</p></article>)}</div></section><section className="content-section services-section section-shell" id="services"><SectionHeading index="07" eyebrow={t('help')} title={t('supportTitle')} intro={t('supportIntro')} /><div className="services-grid">{getServices(locale).map((service, index) => <article className="service-item" key={service.title}><span>0{index + 1}</span><Wrench size={17} /><h3>{service.title}</h3><p>{service.text}</p></article>)}</div></section></>;
}
