'use client';

import { ArrowDownRight, ArrowUpRight, CheckCircle2 } from 'lucide-react';
import { profile } from '../data';
import { useLocale } from '../LocaleProvider';
import { useState } from 'react';
import { WorkModelMap } from './WorkModelMap';

export function Hero() {
  const { t } = useLocale();
  return <section className="hero section-shell" id="top"><div className="hero-copy"><p className="eyebrow"><span className="status-dot" /> {t('available')}</p><h1>{t('heroTitle')} <em>{t('heroAccent')}</em> {t('heroEnd')}</h1><p className="hero-lede">{t('heroLede')}</p><div className="hero-actions"><a className="button button-primary" href="#projects">{t('viewWork')} <ArrowUpRight size={17} /></a><a className="button button-quiet" href="#contact">{t('contactMe')} <ArrowDownRight size={17} /></a></div><div className="hero-proof"><span><CheckCircle2 size={16} /> {t('enterprise')}</span><span><CheckCircle2 size={16} /> {t('kubePractice')}</span><span><CheckCircle2 size={16} /> {t('family')}</span><span><CheckCircle2 size={16} /> {t('workModel')}</span></div><WorkModelMap /></div><ArchitectureVisual /></section>;
}

function ArchitectureVisual() {
  const [hovered, setHovered] = useState(false);
  const [cursorPercent, setCursorPercent] = useState(50);
  const signalState = cursorPercent < 34 ? { label: 'METRIC COLLECTED', value: '1,284', unit: 'rpm', detail: 'http_requests_total' } : cursorPercent < 68 ? { label: 'DASHBOARD SIGNAL', value: '42', unit: 'ms', detail: 'service.response_time' } : { label: 'LOG INVESTIGATION', value: '200', unit: 'status', detail: 'gateway.access 200' };
  return <div className="architecture" aria-label="Interactive cloud-native observability monitor"><div className="arch-label">LIVE SIGNAL <span>{hovered ? 'CURSOR LOCKED' : '24 FPS'}</span></div><div className={hovered ? 'signal-visual is-hovered' : 'signal-visual'} onMouseMove={(event) => { const bounds = event.currentTarget.getBoundingClientRect(); setCursorPercent(((event.clientX - bounds.left) / bounds.width) * 100); }} onMouseEnter={() => setHovered(true)} onMouseLeave={() => setHovered(false)}><div className="signal-topline"><span><i className="live-dot" /> {signalState.label}</span><strong>{hovered ? 'FOCUS' : 'OK'}</strong></div><div className="signal-chart"><div className="chart-grid" /><div className="chart-line chart-line-one" /><div className="chart-line chart-line-two" /><div className="chart-scan" style={{ left: hovered ? `${cursorPercent}%` : undefined }} /><span className="chart-point point-one" /><span className="chart-point point-two" /><span className="chart-point point-three" /></div><div className="signal-readout"><div><small>{signalState.label}</small><strong>{signalState.value} <em>{signalState.unit}</em></strong></div><div><small>CURSOR POSITION</small><strong>{Math.round(cursorPercent)} <em>%</em></strong></div><div><small>ACTIVE EVENT</small><strong>{hovered ? 'LIVE' : 'IDLE'} <em>now</em></strong></div></div><div className="telemetry-panels"><div className="telemetry-panel panel-metric"><div className="panel-heading"><b>METRIC</b><span>01</span></div><strong>1,284 <em>rpm</em></strong><p>http_requests_total</p><i className="mini-bars"><u /><u /><u /><u /><u /><u /><u /></i></div><div className="telemetry-panel panel-trace"><div className="panel-heading"><b>TRACE</b><span>02</span></div><strong>42 <em>ms</em></strong><p>service.response_time</p><i className="trace-path"><u /><u /><u /></i></div><div className="telemetry-panel panel-log"><div className="panel-heading"><b>LOG</b><span>03</span></div><strong>200 <em>status</em></strong><p>gateway.access</p><i className="log-lines"><u /><u /><u /></i></div></div><div className="signal-stream"><div className="stream-row"><span className="stream-time">12:04:31</span><b>metric</b><span>{signalState.detail}</span><i className="activity-bars"><u /><u /><u /><u /><u /></i></div><div className="stream-row"><span className="stream-time">12:04:32</span><b className="stream-blue">trace</b><span>service.response_time</span><i className="activity-bars"><u /><u /><u /><u /><u /></i></div><div className="stream-row"><span className="stream-time">12:04:33</span><b>log</b><span>gateway.access 200</span><i className="activity-bars"><u /><u /><u /><u /><u /></i></div></div></div><div className="arch-footer"><span>{hovered ? 'INSPECTING / HOVER EVENT' : 'OBSERVABILITY / RUNNING'}</span><span className="pulse-line" /></div></div>;
}
