export type Locale = 'en' | 'hu' | 'de';

type TranslationKey = keyof typeof translations.en;

export const translations = {
  en: {
    available: 'Available for selected opportunities', heroTitle: 'I build and operate', heroAccent: 'reliable', heroEnd: 'cloud-native systems.', heroLede: 'DevOps / Cloud-Native Engineer & Application Administrator focused on Kubernetes application operations, Linux systems, observability and delivery workflows in enterprise environments.', viewWork: 'View my work', contactMe: 'Contact me', enterprise: 'Enterprise operations', kubePractice: 'Kubernetes in practice', family: 'Family man and father of two', workModel: 'Full remote preferred; available for two days per week in Budapest',
    mapTitle: 'Where I work from', mapSzeged: 'Szeged', mapBudapest: 'Budapest', mapFullCoverage: 'Home base — full on-site availability', mapTwoDays: '2 days / week on-site in Budapest', mapRemote: 'Remote work available nationwide',
    experience: 'Experience', projectsNav: 'Projects', skillsNav: 'Skills', labNav: 'Lab', educationNav: 'Education', hobbiesNav: 'Hobbies', servicesNav: 'Services', contactNav: 'Contact', letsTalk: "Let's talk", selectedExperience: 'Selected experience', workBehind: 'The work behind the title.', anonymised: 'Anonymised examples of the systems, signals and operational questions I work with.', technology: 'Technology / skills', toolsSignal: 'Tools I use to find the signal.', practicalStack: 'A practical stack built around operating, diagnosing and improving real systems. No percentage bars, just the technologies and concepts behind the work.',
    operationsContext: 'Operations with context.', experienceIntro: 'Three years in an enterprise IT environment, working close to applications, platforms and the teams that build them.', role: 'Application Administrator / DevOps-oriented role', operating: 'Operating and improving business applications in Kubernetes-based environments. My work sits where application behaviour, infrastructure signals and operational process meet.', seeProjects: 'See selected projects', professional: 'Professional experience', caseStudy: 'Case study', platform: 'Platform / infrastructure', challenge: 'Challenge', work: 'Work', outcome: 'Outcome',
    homeLab: 'Home lab', labTitle: 'A small lab for big lessons.', personalLab: 'Personal Kubernetes Lab', practice: 'Practice, break, rebuild.', labText: 'An ongoing environment for keeping operational instincts sharp: Ubuntu Linux nodes, Kubernetes, containers, networking, deployments, services, monitoring and troubleshooting.', labTagNetworking: 'Networking', labTagMonitoring: 'Monitoring', educationLearning: 'Education & learning', nextLayer: 'Building the next layer.', languages: 'Languages', preparing: 'Currently preparing for', longTerm: 'Longer-term interests: Electrical Engineering · IoT · Building Automation · Robotics · Cloud / Infrastructure Security', outside: 'Outside the terminal', hobbiesTitle: 'A few things I make time for.', help: 'How I can help', supportTitle: 'Practical support for growing teams.', supportIntro: 'Focused services for smaller businesses and teams that need dependable foundations without inflated consulting language.', contact: 'Contact', contactTitle: "Let's talk about the system.", contactIntro: 'For roles, collaboration or a practical infrastructure conversation, email is the fastest route.', email: 'Email', linkedin: 'LinkedIn', connect: 'Connect professionally', github: 'GitHub', repos: 'Portfolio repositories coming soon', backTop: 'Back to top', footerTagline: 'DevOps · Cloud-native · Operations', systemView: 'System view', traffic: 'User / traffic', requests: 'HTTP requests', routing: 'Routing layer', runtime: 'Application runtime', observability: 'Observability', metrics: 'Metrics', logs: 'Logs', tracing: 'Tracing',
    eduDegree: 'Computer Engineering / Mérnökinformatika', eduUniversity: 'Gábor Dénes University', eduText: 'Computer networks, operating systems, programming, databases, cloud, IT infrastructure and engineering fundamentals.', learnCka: 'CKA', learnCkaSub: 'Kubernetes certification', learnLinux: 'Linux certification', learnLinuxSub: 'Systems administration track', learnAzure: 'Azure & security', learnAzureSub: 'Cloud and audit direction',
  },
  hu: {
    available: 'Nyitott vagyok kiválasztott lehetőségekre', heroTitle: 'Megbízható cloud-native', heroAccent: 'rendszereket', heroEnd: 'építek és üzemeltetek.', heroLede: 'DevOps / Cloud-Native Engineer és Application Administrator vagyok, Kubernetes-alapú alkalmazásüzemeltetésre, Linux rendszerekre, observabilityre és enterprise delivery folyamatokra fókuszálva.', viewWork: 'Munkáim', contactMe: 'Kapcsolat', enterprise: 'Enterprise üzemeltetés', kubePractice: 'Kubernetes a gyakorlatban', family: 'Családos, két gyermek édesapja', workModel: 'Elsősorban full remote; heti két nap Budapesten vállalható',
    mapTitle: 'Ahonnan dolgozom', mapSzeged: 'Szeged', mapBudapest: 'Budapest', mapFullCoverage: 'Otthoni bázis — teljes helyi bejárás', mapTwoDays: 'Heti 2 nap jelenlét Budapesten', mapRemote: 'Remote munkavégzés az ország egész területén',
    experience: 'Tapasztalat', projectsNav: 'Projektek', skillsNav: 'Készségek', labNav: 'Lab', educationNav: 'Tanulmányok', hobbiesNav: 'Hobbik', servicesNav: 'Szolgáltatások', contactNav: 'Kapcsolat', letsTalk: 'Beszéljünk', selectedExperience: 'Kiemelt tapasztalat', workBehind: 'A cím mögötti valódi munka.', anonymised: 'Anonimizált példák azokról a rendszerekről és üzemeltetési kérdésekről, amelyekkel dolgozom.', technology: 'Technológiák / készségek', toolsSignal: 'Eszközök, amelyekkel megtalálom a jelet.', practicalStack: 'Gyakorlati stack valódi rendszerek üzemeltetésére, diagnosztizálására és fejlesztésére építve.',
    operationsContext: 'Üzemeltetés, összefüggéseiben.', experienceIntro: 'Három év enterprise IT környezetben, közel az alkalmazásokhoz, platformokhoz és az azokat fejlesztő csapatokhoz.', role: 'Application Administrator / DevOps-orientált szerepkör', operating: 'Kubernetes-alapú környezetben futó üzleti alkalmazások üzemeltetése és fejlesztése. A munkám az alkalmazásviselkedés, az infrastruktúra-jelek és az üzemeltetési folyamatok találkozásánál helyezkedik el.', seeProjects: 'Kiemelt projektek', professional: 'Szakmai tapasztalat', caseStudy: 'Esettanulmány', platform: 'Platform / infrastruktúra', challenge: 'Kihívás', work: 'Feladat', outcome: 'Eredmény',
    homeLab: 'Home lab', labTitle: 'Kis lab nagy tanulságokhoz.', personalLab: 'Személyes Kubernetes lab', practice: 'Gyakorlás, törés, újraépítés.', labText: 'Folyamatos gyakorló- és tesztkörnyezet Ubuntu Linux node-okkal, Kubernetes-szel, konténerekkel, hálózatokkal, deploymentekkel, service-ekkel, monitoringgal és hibakereséssel.', labTagNetworking: 'Hálózat', labTagMonitoring: 'Monitoring', educationLearning: 'Tanulmányok és fejlődés', nextLayer: 'A következő réteg építése.', languages: 'Nyelvek', preparing: 'Jelenleg erre készülök', longTerm: 'Hosszabb távú érdeklődés: villamosmérnöki terület · IoT · épületautomatizálás · robotika · cloud / infrastruktúra-biztonság', outside: 'A terminálon kívül', hobbiesTitle: 'Néhány dolog, amire időt szánok.', help: 'Amiben segíthetek', supportTitle: 'Gyakorlati támogatás fejlődő csapatoknak.', supportIntro: 'Fókuszált szolgáltatások kisebb vállalkozásoknak és csapatoknak, megbízható alapokra építve.', contact: 'Kapcsolat', contactTitle: 'Beszéljünk a rendszerről.', contactIntro: 'Pozíció, együttműködés vagy gyakorlati infrastruktúra-kérdés esetén az email a leggyorsabb út.', email: 'Email', linkedin: 'LinkedIn', connect: 'Szakmai kapcsolat', github: 'GitHub', repos: 'A portfólió repozitóriumai hamarosan érkeznek', backTop: 'Vissza a tetejére', footerTagline: 'DevOps · Cloud-native · Üzemeltetés', systemView: 'Rendszernézet', traffic: 'Felhasználó / forgalom', requests: 'HTTP kérések', routing: 'Routing réteg', runtime: 'Alkalmazás runtime', observability: 'Observability', metrics: 'Metrikák', logs: 'Logok', tracing: 'Tracing',
    eduDegree: 'Mérnökinformatika', eduUniversity: 'Gábor Dénes Főiskola', eduText: 'Számítógépes hálózatok, operációs rendszerek, programozás, adatbázisok, cloud, IT infrastruktúra és mérnöki alapok.', learnCka: 'CKA', learnCkaSub: 'Kubernetes minősítés', learnLinux: 'Linux minősítés', learnLinuxSub: 'Rendszergazdai irány', learnAzure: 'Azure és biztonság', learnAzureSub: 'Cloud és audit irány',
  },
  de: {
    available: 'Offen für ausgewählte Möglichkeiten', heroTitle: 'Ich entwickle und betreibe', heroAccent: 'zuverlässige', heroEnd: 'cloud-native Systeme.', heroLede: 'DevOps / Cloud-Native Engineer und Application Administrator mit Fokus auf Kubernetes-Anwendungsbetrieb, Linux-Systeme, Observability und Delivery-Prozesse in Enterprise-Umgebungen.', viewWork: 'Meine Projekte', contactMe: 'Kontakt', enterprise: 'Enterprise-Betrieb', kubePractice: 'Kubernetes in der Praxis', family: 'Familienvater mit zwei Kindern', workModel: 'Full Remote bevorzugt; zwei Tage pro Woche in Budapest möglich',
    mapTitle: 'Von wo aus ich arbeite', mapSzeged: 'Szeged', mapBudapest: 'Budapest', mapFullCoverage: 'Heimatbasis — volle Präsenz vor Ort', mapTwoDays: '2 Tage/Woche vor Ort in Budapest', mapRemote: 'Remote-Arbeit landesweit möglich',
    experience: 'Erfahrung', projectsNav: 'Projekte', skillsNav: 'Skills', labNav: 'Lab', educationNav: 'Ausbildung', hobbiesNav: 'Hobbys', servicesNav: 'Leistungen', contactNav: 'Kontakt', letsTalk: 'Kontakt aufnehmen', selectedExperience: 'Ausgewählte Erfahrung', workBehind: 'Die Arbeit hinter dem Titel.', anonymised: 'Anonymisierte Beispiele für Systeme, Signale und betriebliche Fragestellungen.', technology: 'Technologien / Skills', toolsSignal: 'Werkzeuge, mit denen ich Signale finde.', practicalStack: 'Ein praktischer Stack für den Betrieb, die Diagnose und die Verbesserung realer Systeme.',
    operationsContext: 'Betrieb mit Kontext.', experienceIntro: 'Drei Jahre in einer Enterprise-IT-Umgebung, nah an Anwendungen, Plattformen und den Teams dahinter.', role: 'Application Administrator / DevOps-orientierte Rolle', operating: 'Betrieb und Verbesserung von Geschäftsanwendungen in Kubernetes-Umgebungen. Meine Arbeit verbindet Anwendungsverhalten, Infrastruktur-Signale und betriebliche Prozesse.', seeProjects: 'Projekte ansehen', professional: 'Berufserfahrung', caseStudy: 'Fallstudie', platform: 'Plattform / Infrastruktur', challenge: 'Herausforderung', work: 'Arbeit', outcome: 'Ergebnis',
    homeLab: 'Home Lab', labTitle: 'Ein kleines Lab für große Lektionen.', personalLab: 'Persönliches Kubernetes Lab', practice: 'Üben, brechen, neu aufbauen.', labText: 'Eine laufende Übungs- und Testumgebung mit Ubuntu-Linux-Nodes, Kubernetes, Containern, Netzwerk, Deployments, Services, Monitoring und Troubleshooting.', labTagNetworking: 'Netzwerk', labTagMonitoring: 'Monitoring', educationLearning: 'Ausbildung & Lernen', nextLayer: 'Die nächste Ebene aufbauen.', languages: 'Sprachen', preparing: 'Derzeit in Vorbereitung', longTerm: 'Langfristige Interessen: Elektrotechnik · IoT · Gebäudeautomation · Robotik · Cloud- / Infrastruktur-Sicherheit', outside: 'Außerhalb des Terminals', hobbiesTitle: 'Ein paar Dinge, für die ich Zeit finde.', help: 'Wobei ich helfen kann', supportTitle: 'Praktische Unterstützung für wachsende Teams.', supportIntro: 'Fokussierte Leistungen für kleinere Unternehmen und Teams, die verlässliche Grundlagen brauchen.', contact: 'Kontakt', contactTitle: 'Sprechen wir über das System.', contactIntro: 'Für Rollen, Zusammenarbeit oder ein praktisches Infrastrukturgespräch ist E-Mail der schnellste Weg.', email: 'E-Mail', linkedin: 'LinkedIn', connect: 'Professionell vernetzen', github: 'GitHub', repos: 'Portfolio-Repositories folgen', backTop: 'Nach oben', footerTagline: 'DevOps · Cloud-native · Betrieb', systemView: 'Systemansicht', traffic: 'Nutzer / Traffic', requests: 'HTTP-Anfragen', routing: 'Routing-Schicht', runtime: 'Applikations-Runtime', observability: 'Observability', metrics: 'Metriken', logs: 'Logs', tracing: 'Tracing',
    eduDegree: 'Informatik-Ingenieurwesen', eduUniversity: 'Gábor-Dénes-Hochschule', eduText: 'Computernetzwerke, Betriebssysteme, Programmierung, Datenbanken, Cloud, IT-Infrastruktur und ingenieurwissenschaftliche Grundlagen.', learnCka: 'CKA', learnCkaSub: 'Kubernetes-Zertifizierung', learnLinux: 'Linux-Zertifizierung', learnLinuxSub: 'Systemadministrations-Track', learnAzure: 'Azure & Sicherheit', learnAzureSub: 'Cloud- und Audit-Richtung',
  },
} satisfies Record<Locale, Record<string, string>>;

export function translate(locale: Locale, key: TranslationKey) {
  return translations[locale][key] ?? translations.en[key];
}
